[package]
name = "denim-sam-client"
version = "0.1.0"
edition = "2021"
repository.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
sam-client = { workspace = true }
sam-common = { workspace = true }
tokio = { workspace = true, features = ["full"] }
