coverage:
  range: 60..80
  precision: 2
  status:
    project:
      default: # default is the status check's name, not default settings
        target: 80
        threshold: 20
    patch:
      default:
        target: 80
        threshold: 20

ignore:
  - "**/main.rs"
